# Generated by Django 2.1.5 on 2019-01-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('komplex', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('guest', models.CharField(max_length=100)),
                ('gbmodel', models.IntegerField()),
                ('intdiel', models.IntegerField()),
                ('saltcom', models.FloatField()),
                ('average', models.CharField(max_length=100)),
                ('mmgbsa', models.FloatField()),
                ('nma', models.FloatField()),
                ('deltag', models.FloatField()),
                ('exp', models.FloatField()),
                ('challenge', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('id', 'komplex', 'host', 'guest', 'gbmodel', 'intdiel', 'saltcom', 'average', 'mmgbsa', 'nma', 'deltag', 'exp', 'challenge'),
            },
        ),
    ]
