# Generated by Django 2.1.5 on 2019-01-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexTable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complex',
            options={'ordering': ('id', 'Complex', 'host', 'guest', 'gbmodel', 'intdiel', 'saltcom', 'average', 'mmgbsa', 'nma', 'deltag', 'exp', 'challenge')},
        ),
        migrations.RemoveField(
            model_name='complex',
            name='komplex',
        ),
        migrations.AddField(
            model_name='complex',
            name='Complex',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='complex',
            name='average',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='complex',
            name='challenge',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='complex',
            name='guest',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='complex',
            name='host',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
